### PR TITLE
changed get_string (and GetString) to return "" instead of NULL on EOF

### PR DESCRIPTION
**Pull request by dmalan**
@glennholloway, how's this look to you? @rbowden91 expect this will break any existing `check50` checks?

CC @dlloyd09

### CODE REVIEW

**Comment by kzidane** [comment]
If I may,
1. Is this to get things closer for matching with the C++ version? 
2. Should we have no way to differentiate between an empty-string input and `EOF`?
3. Do we need to change `GetString`, given that it's currently in use by edX students?

**Comment by dmalan** [comment]
1. Indeed, @glennholloway and I concluded that we probably shouldn't have been returning `NULL` in cases of `EOF`, since `EOF` isn't really an error (as would be a `NULL` from `malloc`).
1. So we're disinclined to add another function to the library just to check for that, since it feels like unnecessary complexity. So expecting the caller, if it really cares, to check for `feof(stdin)` is feeling reasonable, even though it breaks the abstraction layer that the library provides.
1. I don't _think_ this change will break things, since I don't _think_ we currently check students' code with `EOF` as an input? Though not sure offhand?

**Comment by dmalan** [comment]
And just to elaborate on your C++ inference... Our hands are indeed even more tied in C++, whereby, if we want to return a `std::string`, we lose the ability to return `NULL` as a sentinel, and an exception would be conventional anyway. But throwing an error in cases of `EOF` doesn't feel right, so returning `""` in cases of `EOF` is feeling like the best way to handle `EOF` across all ports of the library? 

CC @crossroads1112

**Comment by kzidane** [comment]
@dmalan, 

> Indeed, @glennholloway and I concluded that we probably shouldn't have been returning `NULL` in cases of `EOF`, since `EOF` isn't really an error (as would be a `NULL` from `malloc`).

Fwiw, `fgets` returns `NULL` on `EOF` too.

> So we're disinclined to add another function to the library just to check for that, since it feels like unnecessary complexity. So expecting the caller, if it really cares, to check for `feof(stdin)` is feeling reasonable

Is this decided yet? We're gonna need to update the other `get_*` functions accordingly, since they currently expect `get_string` to return `NULL` on `EOF`.

> I don't think this change will break things

No, I don't think we check for that either. Probably not a big deal, but grepped through 2015's and 2016's solutions, and only a couple of solutions might need to be modified to behave exactly the same as before.

**Comment by crossroads1112** [comment]
I apologize for the incredibly late reply. If this is still being considered, I am of the opinion that I would rather see the C and C++ libraries stick to what is idiomatic in their respective languages (as this acclimates students to what it is "really like" to program in them), even if it means slightly different behavior between the two versions. As Kareem points out, it is idiomatic in C to return NULL when there is no meaningful output is supplied. It is somewhat strange to return something that evaluates to "true" when there is nothing more to be read.

**Comment by dmalan** [comment]
Okay, after further thought, going to close this without merging based on the below.

- `get_string` excepted, `get_int` et al. don't have the luxury of returning `NULL` and can only return some sentinel value (e.g., `INT_MAX`) in cases of EOF or error.
- `get_string` currently returns `NULL` in cases of error and EOF. This PR proposed to have it return `""` in cases of EOF instead, but insofar as `get_int` et al. rely on `get_string`, they would then have to decide how to handle cases of `""` and `NULL`, and yet they really only have, e.g., `INT_MAX` as a compelling option for both cases.
- It's worth noting that `gets` returns `NULL` in cases of EOF and error but relies on `feof` and `ferror` to distinguish the two. Introducing our own such mechanisms, though, would unnecessarily complicate an otherwise simple API. `getline`, meanwhile, returns `-1` in cases of EOF and error.

I'm inclined, then, to leave our implementation of `get_string` as is, returning `NULL` in cases of EOF and error and consciously not providing a mechanism (a la `gets`) to distinguish between the two, in large part because doing so has never felt necessary, particularly since these training wheels are ultimately removed mid-semester.

Thanks for all the thoughts!

**Pull request closed without merging**
