### PR TITLE
added static lib, gzipped man pages

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by dmalan** [comment]
Thanks, @kzidane! Pushed a few tweaks to fix permissions. (And capitalized some comments for consistency.)

**Comment by dmalan** [comment]
@kzidane, in `cli50`, if I do

```
sudo apt-get remove -y libcs50
make deb
sudo dpkg -i build/deb/libcs50_10.1.0_amd64.deb
```

I get the below warnings?

```
dpkg: warning: unable to delete old directory '/usr/local/lib': Directory not empty
dpkg: warning: unable to delete old directory '/usr/local/share/man': Directory not empty
dpkg: warning: unable to delete old directory '/usr/local/share': Directory not empty
dpkg: warning: unable to delete old directory '/usr/local/include': Directory not empty
dpkg: warning: unable to delete old directory '/usr/local': Directory not empty
```

**Comment by dmalan** [comment]
Let’s address warnings first, though?

**Comment by kzidane** [comment]
These warnings seem fine. The folders can't be deleted because there's other stuff there (installed by other packages).

**Comment by dmalan** [comment]
Oh I see, it's because `remove` isn't purging all remnants of the older version. If you do

```
sudo apt-get purge -y libcs50
make deb
sudo dpkg -i build/deb/libcs50_10.1.0_amd64.deb
```

there's no warning.

**Comment by kzidane** [comment]
Oh I misread the warning. Sorry!


Kareem

**Pull request merged**
